// <auto-generated />
using System;
using Galeria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galeria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GaleriaDbContext))]
    [Migration("20260813210636_SembrarParametrosNegocio")]
    partial class SembrarParametrosNegocio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Galeria.Domain.Entities.Adelanto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaDescontado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LiquidacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moneda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("Adelantos");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaRecupero")
                        .HasColumnType("TEXT");

                    b.Property<int>("Moneda")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoAlquiler")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoArtista")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoGaleria")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ObraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeAlquiler")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Taller")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelFijo")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtistaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Columna")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pantalla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("ObraId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Tabla", "EntidadId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailDestinatario")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCertificado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ArtistaYaCobro")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.LineaLiquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoObra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.HasIndex("ObraId");

                    b.ToTable("LineasLiquidacion");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Moneda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroCorrelativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodoAnio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAdelantos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDevoluciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("PeriodoAnio", "PeriodoMes");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Moneda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "Fecha");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AltoCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AnchoCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenPrincipalPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LargoCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Moneda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroObra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PagoContado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RubroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TecnicaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TieneIVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Utilidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.HasIndex("SerieId");

                    b.HasIndex("TecnicaId");

                    b.HasIndex("ArtistaId", "NumeroObra")
                        .IsUnique();

                    b.HasIndex("ArtistaId", "Titulo");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Parametro", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Clave");

                    b.ToTable("Parametros");

                    b.HasData(
                        new
                        {
                            Clave = "IvaPorcentaje",
                            Valor = "22"
                        },
                        new
                        {
                            Clave = "RedondeosPesos",
                            Valor = "10"
                        },
                        new
                        {
                            Clave = "RedondeoDolar",
                            Valor = "1"
                        },
                        new
                        {
                            Clave = "UtilidadDefault",
                            Valor = "50"
                        });
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Retiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaEstimadaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ObraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("Retiros");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Tecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tecnicas");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExentaIVA")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Moneda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioCalculado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("ObraId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Adelanto", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Artista", "Artista")
                        .WithMany("Adelantos")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Galeria.Domain.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Adelantos")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artista");

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Alquiler", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Obra", "Obra")
                        .WithMany("Alquileres")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Venta", "Venta")
                        .WithOne("Certificado")
                        .HasForeignKey("Galeria.Domain.Entities.Certificado", "VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Devolucion", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Venta", "Venta")
                        .WithOne("Devolucion")
                        .HasForeignKey("Galeria.Domain.Entities.Devolucion", "VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.LineaLiquidacion", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Lineas")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Galeria.Domain.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Liquidacion");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Liquidacion", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Artista", "Artista")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Obra", "Obra")
                        .WithMany("Movimientos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Obra", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Artista", "Artista")
                        .WithMany("Obras")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Galeria.Domain.Entities.Rubro", "Rubro")
                        .WithMany("Obras")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Galeria.Domain.Entities.Serie", "Serie")
                        .WithMany("Obras")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Galeria.Domain.Entities.Tecnica", "Tecnica")
                        .WithMany("Obras")
                        .HasForeignKey("TecnicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artista");

                    b.Navigation("Rubro");

                    b.Navigation("Serie");

                    b.Navigation("Tecnica");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Retiro", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Obra", "Obra")
                        .WithMany("Retiros")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Serie", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Artista", "Artista")
                        .WithMany("Series")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Venta", b =>
                {
                    b.HasOne("Galeria.Domain.Entities.Obra", "Obra")
                        .WithMany("Ventas")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Artista", b =>
                {
                    b.Navigation("Adelantos");

                    b.Navigation("Liquidaciones");

                    b.Navigation("Obras");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Liquidacion", b =>
                {
                    b.Navigation("Adelantos");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Obra", b =>
                {
                    b.Navigation("Alquileres");

                    b.Navigation("Movimientos");

                    b.Navigation("Retiros");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Rubro", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Serie", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Tecnica", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("Galeria.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Certificado");

                    b.Navigation("Devolucion");
                });
#pragma warning restore 612, 618
        }
    }
}
